# This file was generated by GoReleaser. DO NOT EDIT.
class Fastget < Formula
  desc "A open source cli tool to ultra fast download files over HTTP(S)."
  homepage "https://github.com/pgollangi/fastget"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/pgollangi/fastget/releases/download/v0.1.0/fastget_0.1.0_macOS_amd64.tar.gz"
    sha256 "14fa0899e8cddb53765b00984354cc02de8b3d60cec66cc3ec866435b4b7289a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/fastget/releases/download/v0.1.0/fastget_0.1.0_linux_amd64.tar.gz"
      sha256 "bb83eb3d813d96cb744b05ac8ef28afd51fdcfb4de4388bb783c168f0237ff57"
    end
  end

  def install
    bin.install "bin/fastget"
  end

  test do
    system "#{bin}/fastget version"
  end
end
