# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireql < Formula
  desc "Query Google Firestore database using SQL syntax."
  homepage "https://github.com/pgollangi/FireQL"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.2/fireql_Darwin_x86_64.tar.gz"
      sha256 "d61e4a0825852dba94d77e422df3c1918e6104ee8f53357fff68389c6e3a6183"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.2/fireql_Darwin_arm64.tar.gz"
      sha256 "a85fa124264105195e0460868a8c32d67019defe8052a97eafd737400855906f"

      def install
        bin.install "fireql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.2/fireql_Linux_arm64.tar.gz"
      sha256 "55e712f6a739912fadd66afb7af3548960df01e421bc63f1a01d040d5cdecb7a"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.2/fireql_Linux_x86_64.tar.gz"
      sha256 "c9dd21fdc8cf9dab888c907d8ef25337650502a19ca6ad8ef59199cdcaeafdca"

      def install
        bin.install "fireql"
      end
    end
  end

  test do
    system "#{bin}/fireql --version"
  end
end
