# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireql < Formula
  desc "Query Google Firestore database using SQL syntax."
  homepage "https://github.com/pgollangi/FireQL"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.0/fireql_Darwin_x86_64.tar.gz"
      sha256 "a90057b10e11d8e4a0e5e75449307a33f5b56a9598bdd6ff34c7a1dc85c6b93a"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.0/fireql_Darwin_arm64.tar.gz"
      sha256 "72e629d686290d4ac5c6abf54c71b3e101d2e97e7bf4e92993665c54d108117b"

      def install
        bin.install "fireql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.0/fireql_Linux_x86_64.tar.gz"
      sha256 "0b6ee505fd36853c124672ecfe934c8e41edce67c030473bad824cfd1b670a80"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.0/fireql_Linux_arm64.tar.gz"
      sha256 "b5c707eebf25198f41d57f4a58c386354d30a35bb63da6a1986ab56ce03666af"

      def install
        bin.install "fireql"
      end
    end
  end

  test do
    system "#{bin}/fireql --version"
  end
end
