# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireql < Formula
  desc "Query Google Firestore database using SQL syntax."
  homepage "https://github.com/pgollangi/FireQL"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.1/fireql_Darwin_arm64.tar.gz"
      sha256 "9e0e7b53b5a2d28093057437a017bd5724e5c13313a9a72222b87dad182e9186"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.1/fireql_Darwin_x86_64.tar.gz"
      sha256 "175ca1ae25356f0dfffdd7a2459a527fc11bdae9385588a59e719f7873f92554"

      def install
        bin.install "fireql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.1/fireql_Linux_x86_64.tar.gz"
      sha256 "7d97d622640bc7db072b7842fee9c20f09f74ed8ec0aa8c8c63d0ee83ba624f6"

      def install
        bin.install "fireql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/pgollangi/FireQL/releases/download/v0.2.1/fireql_Linux_arm64.tar.gz"
      sha256 "d7dfc12256f28c7206d30939cb43e4d5a73833d5a5c5c1a175eadd28f9032340"

      def install
        bin.install "fireql"
      end
    end
  end

  test do
    system "#{bin}/fireql --version"
  end
end
