# This file was generated by GoReleaser. DO NOT EDIT.
class Netselect < Formula
  desc "A open source cli tool to find fastest host based on the lowest ICMP latency."
  homepage "https://github.com/pgollangi/netselect"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/pgollangi/netselect/releases/download/v1.1.0/netselect_1.1.0_macOS_amd64.tar.gz"
    sha256 "cdb6c1f00fd6ec9c1cb94eed705c54728df81350f695c41fa70a6a6ed51faf92"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/pgollangi/netselect/releases/download/v1.1.0/netselect_1.1.0_linux_amd64.tar.gz"
      sha256 "bf845a0f48cbfa5bc4306b7e75dd88db865f5453862b79a39b3a89dfb2a91b4c"
    end
  end

  def install
    bin.install "bin/netselect"
  end

  test do
    system "#{bin}/netselect version"
  end
end
